<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QJ8FI0G" ignored="2" name="Car Loan" tests="1" failures="1" timestamp="22 Nov 2019 10:42:53 GMT" time="0.022" errors="0">
  <testcase name="clWebLogin" time="0.016" classname="prep2_Testng.CarLoan">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at prep2_Testng.CarLoan.clWebLogin(CarLoan.java:15)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- clWebLogin -->
  <testcase name="clAPI" time="0.0" classname="prep2_Testng.CarLoan">
    <ignored/>
  </testcase> <!-- clAPI -->
  <testcase name="clMobile" time="0.0" classname="prep2_Testng.CarLoan">
    <ignored/>
  </testcase> <!-- clMobile -->
</testsuite> <!-- Car Loan -->
